- name: PQC Migration Step 12
  hosts: in_vehicle_devices
  gather_facts: false
  vars:
    migrated_nodes:
    - ECU_01.Secure_Onboard_Communication
  tasks:
  - name: Configure and Enable PQC Security Controls
    ansible.builtin.template:
      src: templates/security_controls.conf.j2
      dest: /etc/pqc/controls_step_12.conf
  - name: Restart Migrated Services & Modules
    ansible.builtin.systemd:
      name: pqc_crypto_daemon
      state: restarted
