- name: PQC Migration Step 6
  hosts: localhost
  gather_facts: false
  vars:
    migrated_nodes:
      - Webserver_Classic.TLS_1.2_/_1.3_Communication
  tasks:
    - name: Deploy Post-Quantum Cryptographic Assets & Keys
      ansible.builtin.copy:
        content: >
          # PQC Migrated Keys and Algorithms

          # Node: Webserver_Classic.TLS_1.2_/_1.3_Communication -> Algorithm:
          TLS1.3 (NIST Security Level: 0, Key Size: 0 bytes, Performance:
          UNKNOWN)
        dest: /etc/pqc/keys_step_6.conf
    - name: Restart Migrated Services & Modules
      ansible.builtin.systemd:
        name: pqc_crypto_daemon
        state: restarted
